# Generated by Django 2.2.6 on 2019-11-01 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miniLibrary', '0002_auto_20191101_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='name',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
