# Generated by Django 2.2.6 on 2020-01-03 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miniLibrary', '0004_auto_20200102_1918'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(default='client', max_length=255),
        ),
    ]
